import { ProductType } from "./productType"
import starlink3 from "../../assets/images/productimgs/starlinkGen3.jpg"
import starlink2 from "../../assets/images/productimgs/starlinkGen2.jpg"
import airpod from "../../assets/images/productimgs//airpod1.jpg"
import microwave1 from "../../assets/images/productimgs/microwave1.jpg"
import xiaomi1 from "../../assets/images/productimgs/xiaomi.jpg"
import starlinkMini from "../../assets/images/productimgs/starlinkMini.jpg"
import wirelessMic1 from "../../assets/images/productimgs/wirelessMic.jpg"
import desktop1 from "../../assets/images/productimgs/desktop.jpg"
import supplement1 from "../../assets/images/productimgs/supplement1.jpg"
import stream11 from "../../assets/images/productimgs/stream11Laptop.jpg"
import stream11pro from "../../assets/images/productimgs/stream11proLaptop.jpg"
import hpStream11 from "../../assets/images/productimgs/hpStream11.jpg"
import hpStream11pro from "../../assets/images/productimgs/hpProbook.jpg"
import delMultiTouch1 from "../../assets/images/productimgs/DellMultitouch.jpg"
import Zinox14 from "../../assets/images/productimgs/Zinox Phoenix 14.jpg"
import LenovoIdeapad1 from "../../assets/images/productimgs/Lenovo ideapad.jpg"
import Asus1 from "../../assets/images/productimgs/Asus vivo.jpg"
import DellOptiplex1 from "../../assets/images/productimgs/Dell Optiplex Sff.jpg"
import smartOps1 from "../../assets/images/productimgs/smart Ops.jpg"
import LenovoThinkbook from "../../assets/images/productimgs/Lenovo Thinkbook.jpg"
import V100 from "../../assets/images/productimgs/V100.jpg"
import Thinkcenter1 from "../../assets/images/productimgs/Thinkcenter Neo.jpg"
import Thinkcenter2 from "../../assets/images/productimgs/Thinkcenter Neo2.jpg"
import huwaeiIdeahub1 from "../../assets/images/productimgs/huwaei ideahub.jpg"
import HpElite1 from "../../assets/images/productimgs/HP Elite Sff.webp"
import HPZ41 from "../../assets/images/productimgs/HP Z4 G4.jpg"
import XiaomiRedmi from "../../assets/images/productimgs/Xiaomi Redmi.jpg"
import itelP55 from "../../assets/images/productimgs/itel P55.jpg"
import infinixSmart101 from "../../assets/images/productimgs/infinix smart101.jpg"
import AnkerUsb1 from "../../assets/images/productimgs/AnkerUsb.jpg"
import Oraimo2in1 from "../../assets/images/productimgs/Oraimo2 in 1.jpg"
import OraimoIphoneCable from "../../assets/images/productimgs/Oraimo iphone Cable.jpg"
import Syinix1 from "../../assets/images/productimgs/Syinix 65.jpg"
import samsung1 from "../../assets/images/productimgs/samsung Ua55555.jpg"
import DVP1 from "../../assets/images/productimgs/Sony DVP.jpg"
import DVD1 from "../../assets/images/productimgs/Sony Dvd.jpg"
import femaleGown from "../../assets/images/productimgs/Female Gown.webp"
import womenFashionable1 from "../../assets/images/productimgs/women Fashionable 1.jpg"
import clarksWomen1 from "../../assets/images/productimgs/clarks women Suttyn walk.jpg"
import Haier from "../../assets/images/productimgs/Haier Thermocool.jpg"
import Scanfrost from "../../assets/images/productimgs/Scanfrost.jpg"
import Polyster2in1 from "../../assets/images/productimgs/polyster 2 in 1.jpg"
import synifix2 from "../../assets/images/productimgs/Synifix2.jpg"
import George1 from "../../assets/images/productimgs/George Designed Top and Leggings.webp"
import Nicolette1 from "../../assets/images/productimgs/Nicolette 2-piece cardigan.webp"
import JoyBaby from "../../assets/images/productimgs/Joy Baby.webp"
import DisneyBaby from "../../assets/images/productimgs/Disney Baby.webp"
import CeraveFacial from "../../assets/images/productimgs/cerave facial moisturizer.webp"
import CeraveEye from "../../assets/images/productimgs/cerave eye repair cream.webp"
import Rechargeable from "../../assets/images/productimgs/Dildo Vibrator.webp"
import Dildo from "../../assets/images/productimgs/Rechargeable Dildo.webp"



export const products: ProductType[] = [
    {
        id: 1,
        name: 'Starlink Standard Kit(Gen3)',
        img: starlink3,
        price: 70000,
        discount: 16,
        category: 'computers',
        subCategory: 'Wifi and Networking',
        subType: 'Modems and Mifi',
        rating: 5,
        sameDay: "Same Day Delivery Lagos | Abuja",
        brand :'starlink'
    },
    {
        id: 2,
        name: 'Starlink Standard Actuated Kit (gen 2)',
        img: starlink2,
        price: 590000,
        discount: 29,
        category: 'computers',
        subCategory: 'Wifi and Networking',
        subType: 'Modems and Mifi', 
        rating: 3, 
        sameDay: "Same Day Delivery Lagos | Abuja",
        brand: 'starlink'

    },
    {
        id: 3,
        name: 'Xiaomi Redmi',
        img: xiaomi1,
        price: 138700,
        category: 'phones',
        subCategory: 'Mobile Phones',
        subType: 'Smartphones',
        rating: 3,
                sameDay: "Same Day Delivery Lagos | Abuja"

    },
    {
        id: 4,
        name: 'Starlink Mini',
        img: starlinkMini,
        price: 330000,
        category: 'computers',
        subCategory: 'Wifi and Networking',
        subType: 'Modems and Mifi',
        rating: 3,
                sameDay: "Same Day Delivery Lagos | Abuja",
                brand: 'starlink'

    },
    {
        id: 5,
        name: 'Green Lion  2 in 1 - 360',
        img: femaleGown,
        price: 70000,
        category: 'phones',
        subCategory: 'Mobile Phone Accessories',
        subType: 'earphones & Headsets',
        sponsored: true,
        rating: 2
    },

    {
        id: 6,
        name: 'Vitamin K - 60 Capsules',
        img: supplement1,
        price: 38999,
        discount: 5,
        category: 'beauty',
        subCategory: 'Health',
        subType: 'Medical Supplies & Equipments',
        sponsored: true,
        rating: 4
    },
    {
        id: 7,
        name: 'Wireless Microphone Double',
        img: wirelessMic1,
        price: 15000,
        discount: 7,
        category: 'Electronics',
        subCategory: 'Accessories',
        subType: 'Other Accessories',
        sponsored: true,
    },
    {
        id: 8,
        name: 'Green tiger  2 in 1 - 360',
        img: desktop1,
        price: 60000,
        category: 'phones',
        subCategory: 'Mobile Phone Accessories',
        subType: 'earphones & Headsets',
        sponsored: true,
    },
    {
        id: 9,
        name: 'LG 20 Litres Microwave Touch Screen',
        img: microwave1,
        price: 165360,
        discount: 23,
        rating: 0,
        category: 'kitchen',
        subCategory: 'Kitchen & Dining',
        subType: 'Cookers ',
        sponsored: true,
        brand: 'lg'
    },
    {
        id: 10,
        name: 'HP Stram 11 G4 intel',
        img: stream11,
        price: 185000,
        category: 'computers',
        subCategory: 'Laptops',
        subType: 'Mini Laptops and Netbooks',
        sponsored: true,
        rating: 4,
        brand: 'lg'
    },
    {
        id: 11,
        name: 'xiaomi 11 pro',
        img: xiaomi1,
        price: 145000,
        category: 'computers',
        subCategory: 'Laptops',
        subType: 'Mini Laptops and Netbooks',
        sponsored: true,
        rating: 3,
        brand:'xiaomi'
    },

    {
        id: 12,
        name: 'stream 12 pro inch DvD',
        img: Dildo,
        price: 125000,
        category: 'computers',
        subCategory: 'Laptops',
        subType: 'Mini Laptops and Netbooks',
        sponsored: true,
        rating: 2
    },
    {
        id: 13,
        name: 'stream 13 mini Tony Stark',
        img: delMultiTouch1,
        price: 115000,
        category: 'computers',
        subCategory: 'Laptops',
        subType: 'Mini Laptops and Netbooks',
        sponsored: true,
        sameDay: 'Same Day Delivery Lagos',
        rating: 2
    },
    {
        id: 14,
        name: 'stream 15 pro',
        img: stream11pro,
        price: 225000,
        category: 'computers',
        subCategory: 'Laptops',
        subType: 'Mini Laptops and Netbooks',
        sponsored: true,
        sameDay: 'Same Day Delivery Lagos',
    },
    {
        id: 15,
        name: 'Hp Stream 11 - intel Cele...',
        img: delMultiTouch1,
        price: 140000,
        rating: 0,
        category: 'computers',
        subCategory: 'Laptops',
        subType: 'Mini Laptops and Netbooks',
        soldBy: 'Falana Nation',
        reviewCount: 'No',
        sameDay: 'Same Day Delivery Lagos',
        brand: 'hp'
    },
    {
        id: 16,
        name: 'Hp Stream 11 Pro Mini Laptop',
        img: hpStream11pro,
        price: 175000,
        rating: 3,
        category: 'computers',
        subCategory: 'Laptops',
        subType: 'Mini Laptops and Netbooks',
        soldBy: 'ibksolution',
        reviewCount: 'No',
        sameDay: 'Same Day Delivery Lagos',
        brand: 'hp'

    },
    {
        id: 17,
        name: 'Hp Stream 11 Lunch Mini 1v1',
        img: hpStream11,
        price: 144000,
        rating: 1,
        category: 'computers',
        subCategory: 'Laptops',
        subType: 'Mini Laptops and Netbooks',
        soldBy: 'rayster Nation',
        reviewCount: 'No'
    },

    {
        id: 18,
        name: 'Hp Stream 11 inch Mini Wun',
        img: hpStream11pro,
        price: 105000,
        rating: 0,
        category: 'computers',
        subCategory: 'Laptops',
        subType: 'Mini Laptops and Netbooks',
        soldBy: 'my life',
        reviewCount: 'No'
    },
    {
        id: 19,
        name: 'Dell Multi touch',
        img: delMultiTouch1,
        price: 340000,
        rating: 0,
        category: 'computers',
        subCategory: 'Laptops',
        subType: 'Mini Laptops and Netbooks',
        soldBy: 'Akait Communications',
        reviewCount: 'No',
    },
    {
        id: 20,
        name: 'fukalistik',
        img: hpStream11,
        price: 240000,
        rating: 0,
        category: 'computers',
        subCategory: 'Laptops',
        subType: 'Mini Laptops and Netbooks',
        soldBy: 'ifechukwu',
        reviewCount: 'No',
        sameDay: 'Same Day Delivery Lagos'

    },
    {
        id: 21,
        name: 'Zinox Phoenix 14',
        img: Zinox14,
        price: 1025000,
        discount: 11,
        rating: 3,
        category: 'computers',
        subCategory: 'Laptops',
        subType: 'Notebooks',
        soldBy: 'Konga',
        reviewCount: 'No',
        sameDay: 'same Day Delivery Lagos',
        brand:'zinox'
    },
    {
        id: 22,
        name: 'Lenovo Ideapad 15',
        img: LenovoIdeapad1,
        price: 513000,
        rating: 3,
        category: 'computers',
        subCategory: 'Laptops',
        subType: 'Notebooks',
        soldBy: 'Kay Triple S Computers',
        reviewCount: 'No',
    },
    {
        id: 23,
        name: 'Asus Vivo 15,6',
        img: Asus1,
        price: 650000,
        rating: 1,
        category: 'computers',
        subCategory: 'Laptops',
        subType: 'Notebooks',
        soldBy: 'Tutzie Collections',
        reviewCount: 'No',
    },
    {
        id: 24,
        name: 'okirirka',
        img: Zinox14,
        price: 108000,
        discount: 13,
        rating: 2,
        category: 'computers',
        subCategory: 'Laptops',
        subType: 'Notebooks',
        soldBy: 'shoprite',
        reviewCount: 'No',
        sameDay: 'same Day Delivery Lagos'
    },
    {
        id: 25,
        name: 'zodux',
        img: LenovoIdeapad1,
        price: 313000,
        rating: 5,
        category: 'computers',
        subCategory: 'Laptops',
        subType: 'Notebooks',
        soldBy: 'konga',
        reviewCount: 'No',
    },
    {
        id: 26,
        name: 'Asus Vivo 15,6',
        img: Asus1,
        price: 650000,
        rating: 2,
        category: 'computers',
        subCategory: 'Laptops',
        subType: 'Notebooks',
        soldBy: 'petroleum station',
        reviewCount: 'No',
    },

    {
        id: 27,
        name: 'Dell Optiplex  7010 SFF Desktop',
        img: DellOptiplex1,
        price: 740000,
        rating: 0,
        category: 'computers',
        subCategory: 'Desktops and Monitors',
        subType: 'CPUs',
        soldBy: 'Nnabest Computer',
        reviewCount: 'No',
    },
    {
        id: 28,
        name: 'Smart Ops Pc Module',
        img: smartOps1,
        price: 2460800,
        rating: 0,
        category: 'computers',
        subCategory: 'Desktops and Monitors',
        subType: 'CPUs',
        soldBy: 'Rasonglobal',
        reviewCount: 'No',
    },

    {
        id: 29,
        name: 'HP Z4 G4 W-123',
        img: HPZ41,
        price: 5500000,
        discount: 5,
        rating: 0,
        category: 'computers',
        subCategory: 'Desktops and Monitors',
        subType: 'CPUs',
        soldBy: 'Christ Embassy Integrsted Systems',
        reviewCount: 'No',
        brand:'zte'
    },


    {
        id: 30,
        name: 'Dell Optiplex  7010 SFF Desktop',
        img: DellOptiplex1,
        price: 740000,
        rating: 0,
        category: 'computers',
        subCategory: 'Desktops and Monitors',
        subType: 'CPUs',
        soldBy: 'Nnabest Computer',
        reviewCount: 'No',
    },
    {
        id: 31,
        name: 'Smart Ops Pc Module',
        img: smartOps1,
        price: 2460800,
        rating: 0,
        category: 'computers',
        subCategory: 'Desktops and Monitors',
        subType: 'CPUs',
        soldBy: 'Rasonglobal',
        reviewCount: 'No',
        brand: 'zte'
    },
    {
        id: 32,
        name: 'Smart Ops Pc Module',
        img: smartOps1,
        price: 2460800,
        rating: 0,
        category: 'computers',
        subCategory: 'Desktops and Monitors',
        subType: 'CPUs',
        soldBy: 'Rasonglobal',
        reviewCount: 'No',
    }, {
        id: 33,
        name: 'Lenovo ThinkBook Nbln',
        img: smartOps1,
        price: 812113,
        discount: 2,
        rating: 0,
        category: 'computers',
        subCategory: 'Desktops and Monitors',
        subType: 'All in Ones',
        soldBy: 'Konga',
        reviewCount: 'No',
        sameDay: 'same Day Delivery Lagos'
    },
    {
        id: 34,
        name: 'Lenovo ThinkBook Nbln',
        img: LenovoThinkbook,
        price: 812113,
        discount: 2,
        rating: 0,
        category: 'computers',
        subCategory: 'Desktops and Monitors',
        subType: 'All in Ones',
        soldBy: 'Konga',
        reviewCount: 'No',
        sameDay: 'same Day Delivery Lagos'
    },
    {
        id: 35,
        name: 'Huwaei ideahub B2',
        img: huwaeiIdeahub1,
        price: 5484065,
        discount: 27,
        rating: 0,
        category: 'computers',
        subCategory: 'Desktops and Monitors',
        subType: 'All in Ones',
        soldBy: 'Transform Africa',
        reviewCount: 'No',
        brand: 'huawei'
    },
    {
        id: 36,
        name: 'Hp Elite SFF 600',
        img: HpElite1,
        price: 2100000,
        rating: 0,
        category: 'computers',
        subCategory: 'Desktops and Monitors',
        subType: 'All in Ones',
        soldBy: 'Overflow Computer',
        reviewCount: 'No',
    },
    {
        id: 37,
        name: 'BBL',
        img: LenovoThinkbook,
        price: 80000,
        discount: 2,
        rating: 0,
        category: 'computers',
        subCategory: 'Desktops and Monitors',
        subType: 'All in Ones',
        soldBy: 'ife',
        reviewCount: 'No',
        sameDay: 'same Day Delivery Lagos'
    },
    {
        id: 38,
        name: 'chippmunk',
        img: huwaeiIdeahub1,
        price: 40000,
        discount: 20,
        rating: 0,
        category: 'computers',
        subCategory: 'Desktops and Monitors',
        subType: 'All in Ones',
        soldBy: 'mumu',
        reviewCount: 'No',
    },
    {
        id: 39,
        name: 'loverBoy',
        img: HpElite1,
        price: 4100000,
        rating: 0,
        category: 'computers',
        subCategory: 'Desktops and Monitors',
        subType: 'All in Ones',
        soldBy: 'shagari',
        reviewCount: 'No',
    },
    {
        id: 40,
        name: 'Thinkcenter1 Neo',
        img: Thinkcenter1,
        price: 1001500,
        category: 'computers',
        subCategory: 'Desktops and Monitors',
        subType: 'All in Ones',
        sponsored: true
    }, {
        id: 41,
        name: 'ThinkCenter neoNx x4',
        img: Thinkcenter2,
        price: 882000,
        rating: 0,
        category: 'computers',
        subCategory: 'Desktops and Monitors',
        subType: 'All in Ones',
        sponsored: true
    }, {
        id: 42,
        name: 'Zinox 14',
        img: Zinox14,
        price: 1002000,
        rating: 0,
        category: 'computers',
        subCategory: 'Desktops and Monitors',
        subType: 'All in Ones',
        sponsored: true,
        sameDay: 'Same Day Delivery Lagos',
        brand: 'zinox'
    },
    {
        id: 43,
        name: 'infinix Smart 10HD-',
        img: infinixSmart101,
        price: 106500,
        discount: 10,
        rating: 0,
        category: 'phones',
        subCategory: 'Mobile Phones',
        subType: 'Smartphones',
        soldBy: 'Konga',
        reviewCount: 'No',
        sameDay: 'Same Day Delivery Lagos',
        brand: 'infinix'
    },
    {
        id: 44,
        name: 'Itel P55 - 6.6- 50mp',
        img: itelP55,
        discount: 4,
        price: 120000,
        rating: 5,
        category: 'phones',
        subCategory: 'Mobile Phones',
        subType: 'Smartphones',
        soldBy: 'Konga',
        reviewCount: 1,
    },
    {
        id: 45,
        name: 'Xiaomi Redmi 15C',
        img: XiaomiRedmi,
        price: 174500,
        category: 'phones',
        subCategory: 'Mobile Phones',
        subType: 'Smartphones',
        soldBy: 'Konga',
        reviewCount: 0,
        sameDay: 'Same Day Delivery Lagos',
        brand: 'xiaomi'
    },
    {
        id: 45,
        name: 'Tecno Smart 10HD-',
        img: infinixSmart101,
        price: 206500,
        discount: 10,
        rating: 0,
        category: 'phones',
        subCategory: 'Mobile Phones',
        subType: 'Smartphones',
        soldBy: 'ode niye',
        reviewCount: 'No',
        brand: 'tecno'
    },
    {
        id: 46,
        name: 'iphone P55 - 6.6- 50mp',
        img: itelP55,
        discount: 4,
        price: 250000,
        rating: 5,
        category: 'phones',
        subCategory: 'Mobile Phones',
        subType: 'Smartphones',
        soldBy: 'Konga',
        reviewCount: 0,
        sameDay: 'Same Day Delivery Lagos'
    },
    {
        id: 47,
        name: 'johnpaul Redmi 15C',
        img: XiaomiRedmi,
        price: 194500,
        category: 'phones',
        subCategory: 'Mobile Phones',
        subType: 'Smartphones',
        soldBy: 'Konga',
        reviewCount: 0,
    },
    {
        id: 48,
        name: 'Anker Usb C Cable- 100w',
        img: AnkerUsb1,
        price: 28000,
        discount: 4,
        rating: 0,
        category: 'phones',
        subCategory: 'Mobile Phones',
        subType: 'Smartphones',
        soldBy: 'yomilincon',
        reviewCount: 'No'
    },
    {
        id: 49,
        name: 'Oraimo2 in 1 Cord Ocd -d62',
        img: Oraimo2in1,
        price: 3600,
        discount: 3,
        rating: 0,
        category: 'phones',
        subCategory: 'Mobile Phones',
        subType: 'Smartphones',
        soldBy: 'yomilincon',
        reviewCount: 'No',
        sameDay: 'Same Day Delivery Lagos'

    },
    {
        id: 50,
        name: 'Oraimo IPhone Cable Ocd-153',
        img: OraimoIphoneCable,
        price: 6000,
        discount: 8,
        rating: 0,
        category: 'phones',
        subCategory: 'Mobile Phones',
        subType: 'Smartphones',
        soldBy: 'yomilincon',
        reviewCount: 'No'
    },
    {
        id: 51,
        name: 'Samsung Ua55u800',
        img: samsung1,
        price: 790000,
        rating: 0,
        category: 'Electronics',
        subCategory: 'Televisions',
        subType: 'Smart TVs',
        soldBy: 'konga',
        reviewCount: 'No',
        sameDay: 'Same Day Delivery Lagos'
    },
    {
        id: 52,
        name: 'Syinix Android 4k',
        img: Syinix1,
        price: 850000,
        discount: 8,
        rating: 0,
        category: 'Electronics',
        subCategory: 'Televisions',
        subType: 'Smart TVs',
        soldBy: 'yomilincon',
        reviewCount: 1,
        sameDay: 'Same Day Delivery Lagos',
        sponsored:true
    },
    {
        id: 53,
        name: 'Sony DVP SR370 Multisystem DVD player',
        img: DVP1,
        price: 146000,
        discount: 1,
        rating: 0,
        category: 'Electronics',
        subCategory: 'DVD Players and Recorders',
        subType: 'DVD players',
        soldBy: 'yomilincon Brand',
        reviewCount: 0,
        sponsored: true
    },
    {
        id: 54,
        name: 'Sony DVD Player with Mp3',
        img: DVD1,
        price: 29999,
        rating: 0,
        category: 'Electronics',
        subCategory: 'DVD Players and Recorders',
        subType: 'DVD players',
        soldBy: 'Emart Collections',
        reviewCount: 0,
    },
    {
        id: 55,
        name: 'Female Gown',
        img: femaleGown,
        price: 8999,
        category: 'kongafashion',
        subCategory: 'Womens Wear',
        subType: 'Dresses',
        soldBy: 'Allahu Lateef Stores',
        reviewCount: 0,
    },
    {
        id: 56,
        name: 'Turkey Dress',
        img: femaleGown,
        price: 30000,
        category: 'kongafashion',
        subCategory: 'Womens Wear',
        subType: 'Dresses',
        soldBy: 'Hillwave Solutions',
        reviewCount: 0,
    },
    {
        id: 57,
        name: 'Clarks Women Suttyn',
        img: femaleGown,
        price: 140000,
        discount: 36,
        category: 'kongafashion',
        subCategory: 'Womens Wear',
        subType: 'Dresses',
        soldBy: 'Joots internationale',
        reviewCount: 0,
    },
    {
        id: 58,
        name: 'Clarks Women Suttyn',
        img: clarksWomen1,
        price: 140000,
        discount: 36,
        category: 'kongafashion',
        subCategory: 'Womens Wear',
        subType: 'Dresses',
        soldBy: 'Joots internationale',
        reviewCount: 0,
    },
    {
        id: 59,
        name: 'Women Fashionable Thick Bottom Wedge slippers',
        img: womenFashionable1,
        price: 28000,
        discount: 14,
        category: 'kongafashion',
        subCategory: 'Womens Wear',
        subType: 'Dresses',
        soldBy: 'Tansemah Clothing',
        reviewCount: 0,
    },

    {
        id: 60,
        name: 'Clarks Women Suttyn',
        img: clarksWomen1,
        price: 140000,
        discount: 36,
        category: 'kongafashion',
        subCategory: 'Womens Wear',
        subType: 'Dresses',
        soldBy: 'Joots internationale',
        reviewCount: 0,
        sameDay: 'Same Day Delivery Lagos'
    },
    {
        id: 61,
        name: 'Clarks Women Suttyn',
        img: clarksWomen1,
        price: 140000,
        discount: 36,
        category: 'kongafashion',
        subCategory: 'Womens Wear',
        subType: 'Dresses',
        soldBy: 'Joots internationale',
        reviewCount: 0,
        sameDay: 'Same Day Delivery Lagos'
    },
    {
        id: 62,
        name: 'Haier Thermocool Ht Ac Split',
        img: Haier,
        price: 652150,
        discount: 39,
        category: 'kitchen',
        subCategory: 'Large Appliances',
        subType: 'Air Conditioners & Coolers',
        soldBy: 'Konga',
        reviewCount: 0,
        sameDay: 'Same Day Delivery Lagos'
    },
    {
        id: 63,
        name: 'Scanfrost 1hp Air Conditioner sfacs9m',
        img: Scanfrost,
        price: 373000,
        discount: 12,
        category: 'kitchen',
        subCategory: 'Large Appliances',
        subType: 'Air Conditioners & Coolers',
        soldBy: 'Konga',
        reviewCount: 2,
        rating: 4,
        sameDay: "Same Day Delivery Lagos",
        sponsored: true
    },
    {
        id: 64,
        name: 'Yansh Thermocool Ht Ac Split',
        img: Haier,
        price: 70000,
        discount: 20,
        category: 'kitchen',
        subCategory: 'Large Appliances',
        subType: 'Air Conditioners & Coolers',
        soldBy: 'ife',
        reviewCount: 0,
        brand: 'thermocool'
    },
    {
        id: 65,
        name: 'Polystar 2 in 1 Blender',
        img: Polyster2in1,
        price: 40150,
        discount: 35,
        category: 'kitchen',
        subCategory: 'Small Appliance',
        subType: 'Blenders Juicers & Mixers',
        soldBy: 'Konga',
        reviewCount: 2,
        rating: 4,
        sameDay: "Same Day Delivery Lagos"
    },
    {
        id: 66,
        name: 'Synix Sfm50e1',
        img: synifix2,
        price: 134140,
        discount: 15,
        category: 'kitchen',
        subCategory: 'Small Appliance',
        subType: 'Blenders Juicers & Mixers',
        soldBy: 'Konga',
        reviewCount: 'NO',
        rating: 4,
        sameDay: "Same Day Delivery Lagos"
    },
    {
        id: 67,
        name: 'Polystar 2 in 1 Blender',
        img: Polyster2in1,
        price: 40150,
        discount: 35,
        category: 'kitchen',
        subCategory: 'Small Appliance',
        subType: 'Blenders Juicers & Mixers',
        soldBy: 'Konga',
        reviewCount: 2,
        rating: 4,
        sameDay: "Same Day Delivery Lagos"
    },
    {
        id: 68,
        name: 'Synix Sfm50e1',
        img: synifix2,
        price: 134140,
        discount: 15,
        category: 'kitchen',
        subCategory: 'Small Appliance',
        subType: 'Blenders, Juicers & Mixers',
        soldBy: 'Konga',
        reviewCount: 'NO',
        rating: 4,
        sameDay: "Same Day Delivery Lagos"
    },
    {
        id: 69,
        name: 'Polystar 2 in 1 Blender',
        img: Polyster2in1,
        price: 40150,
        discount: 35,
        category: 'kitchen',
        subCategory: 'Small Appliance',
        subType: 'Blenders, Juicers & Mixers',
        soldBy: 'Konga',
        reviewCount: 2,
        rating: 4,
        sameDay: "Same Day Delivery Lagos"
    },
    {
        id: 70,
        name: 'George Designed Top and Leggings',
        img: George1,
        price: 5000,
        discount: 4,
        category: 'baby',
        subCategory: 'Fashion for Girls',
        subType: 'Sets',
        soldBy: 'cantalopue',
        reviewCount: 'NO',
        rating: 0,
    },
    {
        id: 71,
        name: 'Nicolette 2-piece Cardigan & Dress Set - Blue',
        img: femaleGown,
        price: 12500,
        category: 'baby',
        subCategory: 'Fashion for Girls',
        subType: 'Sets',
        soldBy: 'exquisite Deals',
        reviewCount: 'NO',
        rating: 0,
    },
    {
        id: 72,
        name: 'George Designed Top and Leggings',
        img: George1,
        price: 5000,
        discount: 4,
        category: 'baby',
        subCategory: 'Fashion for Girls',
        subType: 'Sets',
        soldBy: 'cantalopue',
        reviewCount: 'NO',
        rating: 0,
    },
    {
        id: 73,
        name: 'Nicolette 2-piece Cardigan & Dress Set - Blue',
        img: Dildo,
        price: 12500,
        category: 'baby',
        subCategory: 'Fashion for Girls',
        subType: 'Sets',
        soldBy: 'exquisite Deals',
        reviewCount: 'NO',
        rating: 0,
    },

    {
        id: 74,
        name: 'Nicolette 2-piece Cardigan & Dress Set - Blue',
        img: Nicolette1,
        price: 12500,
        category: 'baby',
        subCategory: 'Baby Essentials',
        subType: 'Nursery',
        soldBy: 'exquisite Deals',
        reviewCount: 'NO',
        rating: 0,
    },
    {
        id: 75,
        name: 'Joy baby Foldable Mobile Bed With Net',
        img: JoyBaby,
        price: 8500,
        category: 'baby',
        subCategory: 'Baby Essentials',
        subType: 'Nursery',
        soldBy: 'Great Home Mall',
        reviewCount: 'NO',
        rating: 0,
    },
    {
        id: 76,
        name: 'Disney Baby Sweet wonder Baby Play Yard With',
        img: DisneyBaby,
        price: 180000,
        category: 'baby',
        subCategory: 'Baby Essentials',
        subType: 'Nursery',
        soldBy: 'Dailygrace Boutique',
        reviewCount: 'NO',
        rating: 0,
    },
    {
        id: 77,
        name: 'Bed With Net',
        img: JoyBaby,
        price: 18500,
        category: 'baby',
        subCategory: 'Baby Essentials',
        subType: 'Nursery',
        soldBy: 'Great Home',
        reviewCount: 'NO',
        rating: 0,
    },
    {
        id: 78,
        name: 'Disney Baby Sweet wonder Baby Play Yard With',
        img: DisneyBaby,
        price: 180000,
        category: 'baby',
        subCategory: 'Baby Essentials',
        subType: 'Nursery',
        soldBy: 'Dailygrace Boutique',
        reviewCount: 'NO',
        rating: 0,
    },
    {
        id: 79,
        name: 'Cerave Facial Moisturizer for Normal Dry Skin',
        img: CeraveFacial,
        price: 26005,
        category: 'beauty',
        subCategory: 'Dermatological Skincare',
        subType: 'Facial Moisturizer',
        soldBy: 'Konga  H-Plus',
        reviewCount: 'NO',
        rating: 0,
        sameDay: "Same Day Delivery Lagos"
    },
    {
        id: 80,
        name: 'Cerave Eye Repair Cream with 3 Essentials',
        img: CeraveEye,
        price: 20760,
        category: 'beauty',
        subCategory: 'Dermatological Skincare',
        subType: 'Facial Moisturizer',
        soldBy: 'Konga  H-Plus',
        reviewCount: 'NO',
        rating: 0,
        sameDay: "Same Day Delivery Lagos"
    },

    {
        id: 81,
        name: 'Cerave Facial Moisturizer for Normal Dry Skin',
        img: CeraveFacial,
        price: 26005,
        category: 'beauty',
        subCategory: 'Dermatological Skincare',
        subType: 'Facial Moisturizer',
        soldBy: 'Konga  H-Plus',
        reviewCount: 'NO',
        rating: 0,
    },
    {
        id: 82,
        name: 'Cerave Eye Repair Cream with 3 Essentials',
        img: CeraveEye,
        price: 20760,
        category: 'beauty',
        subCategory: 'Dermatological Skincare',
        subType: 'Facial Moisturizer',
        soldBy: 'Konga  H-Plus',
        reviewCount: 'NO',
        rating: 0,

    },
    {
        id: 83,
        name: 'Rechargeable dildo massager',
        img: Rechargeable,
        price: 25000,
        category: 'beauty',
        subCategory: 'Sexual Wellness',
        subType: 'Adult Toys',
        soldBy: 'Konga  H-Plus',
        reviewCount: 'NO',
        rating: 0,
        sameDay: "Same Day Delivery Lagos",
    },
    {
        id: 84,
        name: 'Dildo Vibrator Women - Vaginal Sex Toy',
        img: Dildo,
        price: 25000,
        category: 'beauty',
        subCategory: 'Sexual Wellness',
        subType: 'Adult Toys',
        soldBy: 'Konga  H-Plus',
        reviewCount: 'NO',
        rating: 0,
        sameDay: "Same Day Delivery Lagos",
    },

    {
        id: 85,
        name: 'Rechargeable dildo massager',
        img: Rechargeable,
        price: 25000,
        category: 'beauty',
        subCategory: 'Sexual Wellness',
        subType: 'Adult Toys',
        soldBy: 'Sold to Work Online',
        reviewCount: 'NO',
        rating: 0,
        sameDay: "Same Day Delivery Lagos"
    },
    {
        id: 86,
        name: 'Dildo Vibrator Women - Vaginal Sex Toy',
        img: Dildo,
        price: 10000,
        discount: 20,
        category: 'beauty',
        subCategory: 'Sexual Wellness',
        subType: 'Adult Toys',
        soldBy: 'Konga  H-Plus',
        reviewCount: 'NO',
        rating: 0,
        sameDay: "Same Day Delivery Lagos"
    },
    {
        id: 87,
        name: 'cables',
        img: Dildo,
        price: 10000,
        discount: 20,
        category: 'phones',
        subCategory: 'Mobile Phone Accessories',
        subType: 'Cables',
        soldBy: 'Konga  H-Plus',
        reviewCount: 'NO',
        rating: 0,
        sameDay: "Same Day Delivery Lagos"
    },
    {
        id: 88,
        name: 'cables2',
        img: Rechargeable,
        price: 400000,
        discount: 20,
        category: 'phones',
        subCategory: 'Mobile Phone Accessories',
        subType: 'Cables',
        soldBy: 'Konga  H-Plus',
        reviewCount: 'NO',
        rating: 0,
        sameDay: "Same Day Delivery Lagos",
    },
    {
        id: 89,
        name: 'cables',
        img: Dildo,
        price: 10000,
        discount: 20,
        category: 'phones',
        subCategory: 'Mobile Phone Accessories',
        subType: 'Cables',
        soldBy: 'Konga  H-Plus',
        reviewCount: 'NO',
        rating: 0,
        sameDay: "Same Day Delivery Lagos"
    },
    {
        id: 90,
        name: 'cables2',
        img: Rechargeable,
        price: 400000,
        discount: 20,
        category: 'phones',
        subCategory: 'Mobile Phone Accessories',
        subType: 'Cables',
        soldBy: 'Konga  H-Plus',
        reviewCount: 'NO',
        rating: 0,
        sameDay: "Same Day Delivery Lagos"
    },
        {
        id: 91,
        name: 'Tecno 11 pro',
        img: xiaomi1,
        price: 105000,
        category: 'computers',
        subCategory: 'Laptops',
        subType: 'Mini Laptops and Netbooks',
        sponsored: true,
        rating: 3,
        brand: 'tecno'
    },
     {
        id: 92,
        name: 'Infinix Hot 30 Play',
        img: itelP55,
        discount: 4,
        price: 70000,
        rating: 5,
        category: 'phones',
        subCategory: 'Mobile Phones',
        subType: 'Smartphones',
        soldBy: 'Konga',
        reviewCount: 0,
        sameDay: 'Same Day Delivery Lagos',
        brand: 'infinix'

    },

]